---
- name: Install Kibana plugins
  become: true
  become_user: kibana
  command: /usr/share/kibana/bin/kibana-plugin install {{ item.url }}
  args:
    creates: /usr/share/kibana/plugins/{{ item.name }}
  with_items:
    - "{{ kibana_plugins }}"
  notify: restart kibana
