version: 2
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run: pip install --upgrade setuptools
          name: install-depedencies
          command: 'pip install --upgrade setuptools && \
                    pip install ansible && \
                    pip install docker && \
                    pip install molecule'

  test:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run:
          name: run-molecule
          command: molecule test --driver docker
